services:
  app:
    build: .
    ports:
      - '8000:80'

  titiler:
    image: ghcr.io/ninanor/titiler-app-titiler:next
    environment:
      - TITILER_API_CORS_ORIGINS=*
      - TITILER_API_CACHECONTROL=no-cache
      - TITILER_API_ROOT_PATH=/titiler
      - FORWARDED_ALLOW_IPS=*
      - REDIS_HOST=redis
    ports:
      - '8989:80'

  redis:
    image: redis
