/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutManageRouteImport } from './routes/_pathlessLayout/manage'
import { Route as PathlessLayoutLegendRouteImport } from './routes/_pathlessLayout/legend'
import { Route as PathlessLayoutDescriptionRouteImport } from './routes/_pathlessLayout/description'
import { Route as PathlessLayoutBasemapRouteImport } from './routes/_pathlessLayout/basemap'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutManageRoute = PathlessLayoutManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutLegendRoute = PathlessLayoutLegendRouteImport.update({
  id: '/legend',
  path: '/legend',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutDescriptionRoute =
  PathlessLayoutDescriptionRouteImport.update({
    id: '/description',
    path: '/description',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutBasemapRoute = PathlessLayoutBasemapRouteImport.update({
  id: '/basemap',
  path: '/basemap',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/basemap': typeof PathlessLayoutBasemapRoute
  '/description': typeof PathlessLayoutDescriptionRoute
  '/legend': typeof PathlessLayoutLegendRoute
  '/manage': typeof PathlessLayoutManageRoute
  '/': typeof PathlessLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/basemap': typeof PathlessLayoutBasemapRoute
  '/description': typeof PathlessLayoutDescriptionRoute
  '/legend': typeof PathlessLayoutLegendRoute
  '/manage': typeof PathlessLayoutManageRoute
  '/': typeof PathlessLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/basemap': typeof PathlessLayoutBasemapRoute
  '/_pathlessLayout/description': typeof PathlessLayoutDescriptionRoute
  '/_pathlessLayout/legend': typeof PathlessLayoutLegendRoute
  '/_pathlessLayout/manage': typeof PathlessLayoutManageRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/basemap' | '/description' | '/legend' | '/manage' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/basemap' | '/description' | '/legend' | '/manage' | '/'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/basemap'
    | '/_pathlessLayout/description'
    | '/_pathlessLayout/legend'
    | '/_pathlessLayout/manage'
    | '/_pathlessLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/manage': {
      id: '/_pathlessLayout/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof PathlessLayoutManageRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/legend': {
      id: '/_pathlessLayout/legend'
      path: '/legend'
      fullPath: '/legend'
      preLoaderRoute: typeof PathlessLayoutLegendRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/description': {
      id: '/_pathlessLayout/description'
      path: '/description'
      fullPath: '/description'
      preLoaderRoute: typeof PathlessLayoutDescriptionRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/basemap': {
      id: '/_pathlessLayout/basemap'
      path: '/basemap'
      fullPath: '/basemap'
      preLoaderRoute: typeof PathlessLayoutBasemapRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutBasemapRoute: typeof PathlessLayoutBasemapRoute
  PathlessLayoutDescriptionRoute: typeof PathlessLayoutDescriptionRoute
  PathlessLayoutLegendRoute: typeof PathlessLayoutLegendRoute
  PathlessLayoutManageRoute: typeof PathlessLayoutManageRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutBasemapRoute: PathlessLayoutBasemapRoute,
  PathlessLayoutDescriptionRoute: PathlessLayoutDescriptionRoute,
  PathlessLayoutLegendRoute: PathlessLayoutLegendRoute,
  PathlessLayoutManageRoute: PathlessLayoutManageRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
