/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as MapIdRouteImport } from './routes/$mapId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorLayoutRouteImport } from './routes/editor/_layout'
import { Route as MapIdLayoutRouteImport } from './routes/$mapId/_layout'
import { Route as EditorLayoutEditRouteImport } from './routes/editor/_layout/edit'
import { Route as EditorLayoutViewRouteImport } from './routes/editor/_layout/_view'
import { Route as MapIdLayoutViewRouteImport } from './routes/$mapId/_layout/_view'
import { Route as EditorLayoutEditIndexRouteImport } from './routes/editor/_layout/edit/index'
import { Route as EditorLayoutViewIndexRouteImport } from './routes/editor/_layout/_view/index'
import { Route as MapIdLayoutViewIndexRouteImport } from './routes/$mapId/_layout/_view/index'
import { Route as EditorLayoutEditSettingsRouteImport } from './routes/editor/_layout/edit/settings'
import { Route as EditorLayoutEditManageRouteImport } from './routes/editor/_layout/edit/manage'
import { Route as EditorLayoutEditDescriptionRouteImport } from './routes/editor/_layout/edit/description'
import { Route as EditorLayoutEditBasemapRouteImport } from './routes/editor/_layout/edit/basemap'
import { Route as EditorLayoutViewManageRouteImport } from './routes/editor/_layout/_view/manage'
import { Route as EditorLayoutViewLegendRouteImport } from './routes/editor/_layout/_view/legend'
import { Route as EditorLayoutViewDescriptionRouteImport } from './routes/editor/_layout/_view/description'
import { Route as EditorLayoutViewBasemapRouteImport } from './routes/editor/_layout/_view/basemap'
import { Route as MapIdLayoutViewManageRouteImport } from './routes/$mapId/_layout/_view/manage'
import { Route as MapIdLayoutViewLegendRouteImport } from './routes/$mapId/_layout/_view/legend'
import { Route as MapIdLayoutViewDescriptionRouteImport } from './routes/$mapId/_layout/_view/description'
import { Route as MapIdLayoutViewBasemapRouteImport } from './routes/$mapId/_layout/_view/basemap'
import { Route as EditorLayoutEditLayersAddRouteImport } from './routes/editor/_layout/edit/layers.add'
import { Route as EditorLayoutEditLayersLayerIdRouteImport } from './routes/editor/_layout/edit/layers.$layerId'
import { Route as EditorLayoutEditFoldersAddRouteImport } from './routes/editor/_layout/edit/folders.add'
import { Route as EditorLayoutEditFoldersFolderIdRouteImport } from './routes/editor/_layout/edit/folders.$folderId'
import { Route as EditorLayoutViewLayersLayerIdRouteImport } from './routes/editor/_layout/_view/layers.$layerId'
import { Route as EditorLayoutViewFoldersFolderIdRouteImport } from './routes/editor/_layout/_view/folders.$folderId'
import { Route as MapIdLayoutViewLayersLayerIdRouteImport } from './routes/$mapId/_layout/_view/layers.$layerId'
import { Route as MapIdLayoutViewFoldersFolderIdRouteImport } from './routes/$mapId/_layout/_view/folders.$folderId'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIdRoute = MapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorLayoutRoute = EditorLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EditorRoute,
} as any)
const MapIdLayoutRoute = MapIdLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => MapIdRoute,
} as any)
const EditorLayoutEditRoute = EditorLayoutEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EditorLayoutRoute,
} as any)
const EditorLayoutViewRoute = EditorLayoutViewRouteImport.update({
  id: '/_view',
  getParentRoute: () => EditorLayoutRoute,
} as any)
const MapIdLayoutViewRoute = MapIdLayoutViewRouteImport.update({
  id: '/_view',
  getParentRoute: () => MapIdLayoutRoute,
} as any)
const EditorLayoutEditIndexRoute = EditorLayoutEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorLayoutEditRoute,
} as any)
const EditorLayoutViewIndexRoute = EditorLayoutViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorLayoutViewRoute,
} as any)
const MapIdLayoutViewIndexRoute = MapIdLayoutViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapIdLayoutViewRoute,
} as any)
const EditorLayoutEditSettingsRoute =
  EditorLayoutEditSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutEditManageRoute = EditorLayoutEditManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => EditorLayoutEditRoute,
} as any)
const EditorLayoutEditDescriptionRoute =
  EditorLayoutEditDescriptionRouteImport.update({
    id: '/description',
    path: '/description',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutEditBasemapRoute = EditorLayoutEditBasemapRouteImport.update({
  id: '/basemap',
  path: '/basemap',
  getParentRoute: () => EditorLayoutEditRoute,
} as any)
const EditorLayoutViewManageRoute = EditorLayoutViewManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => EditorLayoutViewRoute,
} as any)
const EditorLayoutViewLegendRoute = EditorLayoutViewLegendRouteImport.update({
  id: '/legend',
  path: '/legend',
  getParentRoute: () => EditorLayoutViewRoute,
} as any)
const EditorLayoutViewDescriptionRoute =
  EditorLayoutViewDescriptionRouteImport.update({
    id: '/description',
    path: '/description',
    getParentRoute: () => EditorLayoutViewRoute,
  } as any)
const EditorLayoutViewBasemapRoute = EditorLayoutViewBasemapRouteImport.update({
  id: '/basemap',
  path: '/basemap',
  getParentRoute: () => EditorLayoutViewRoute,
} as any)
const MapIdLayoutViewManageRoute = MapIdLayoutViewManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => MapIdLayoutViewRoute,
} as any)
const MapIdLayoutViewLegendRoute = MapIdLayoutViewLegendRouteImport.update({
  id: '/legend',
  path: '/legend',
  getParentRoute: () => MapIdLayoutViewRoute,
} as any)
const MapIdLayoutViewDescriptionRoute =
  MapIdLayoutViewDescriptionRouteImport.update({
    id: '/description',
    path: '/description',
    getParentRoute: () => MapIdLayoutViewRoute,
  } as any)
const MapIdLayoutViewBasemapRoute = MapIdLayoutViewBasemapRouteImport.update({
  id: '/basemap',
  path: '/basemap',
  getParentRoute: () => MapIdLayoutViewRoute,
} as any)
const EditorLayoutEditLayersAddRoute =
  EditorLayoutEditLayersAddRouteImport.update({
    id: '/layers/add',
    path: '/layers/add',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutEditLayersLayerIdRoute =
  EditorLayoutEditLayersLayerIdRouteImport.update({
    id: '/layers/$layerId',
    path: '/layers/$layerId',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutEditFoldersAddRoute =
  EditorLayoutEditFoldersAddRouteImport.update({
    id: '/folders/add',
    path: '/folders/add',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutEditFoldersFolderIdRoute =
  EditorLayoutEditFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => EditorLayoutEditRoute,
  } as any)
const EditorLayoutViewLayersLayerIdRoute =
  EditorLayoutViewLayersLayerIdRouteImport.update({
    id: '/layers/$layerId',
    path: '/layers/$layerId',
    getParentRoute: () => EditorLayoutViewRoute,
  } as any)
const EditorLayoutViewFoldersFolderIdRoute =
  EditorLayoutViewFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => EditorLayoutViewRoute,
  } as any)
const MapIdLayoutViewLayersLayerIdRoute =
  MapIdLayoutViewLayersLayerIdRouteImport.update({
    id: '/layers/$layerId',
    path: '/layers/$layerId',
    getParentRoute: () => MapIdLayoutViewRoute,
  } as any)
const MapIdLayoutViewFoldersFolderIdRoute =
  MapIdLayoutViewFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => MapIdLayoutViewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mapId': typeof MapIdLayoutViewRouteWithChildren
  '/editor': typeof EditorLayoutViewRouteWithChildren
  '/editor/edit': typeof EditorLayoutEditRouteWithChildren
  '/$mapId/basemap': typeof MapIdLayoutViewBasemapRoute
  '/$mapId/description': typeof MapIdLayoutViewDescriptionRoute
  '/$mapId/legend': typeof MapIdLayoutViewLegendRoute
  '/$mapId/manage': typeof MapIdLayoutViewManageRoute
  '/editor/basemap': typeof EditorLayoutViewBasemapRoute
  '/editor/description': typeof EditorLayoutViewDescriptionRoute
  '/editor/legend': typeof EditorLayoutViewLegendRoute
  '/editor/manage': typeof EditorLayoutViewManageRoute
  '/editor/edit/basemap': typeof EditorLayoutEditBasemapRoute
  '/editor/edit/description': typeof EditorLayoutEditDescriptionRoute
  '/editor/edit/manage': typeof EditorLayoutEditManageRoute
  '/editor/edit/settings': typeof EditorLayoutEditSettingsRoute
  '/$mapId/': typeof MapIdLayoutViewIndexRoute
  '/editor/': typeof EditorLayoutViewIndexRoute
  '/editor/edit/': typeof EditorLayoutEditIndexRoute
  '/$mapId/folders/$folderId': typeof MapIdLayoutViewFoldersFolderIdRoute
  '/$mapId/layers/$layerId': typeof MapIdLayoutViewLayersLayerIdRoute
  '/editor/folders/$folderId': typeof EditorLayoutViewFoldersFolderIdRoute
  '/editor/layers/$layerId': typeof EditorLayoutViewLayersLayerIdRoute
  '/editor/edit/folders/$folderId': typeof EditorLayoutEditFoldersFolderIdRoute
  '/editor/edit/folders/add': typeof EditorLayoutEditFoldersAddRoute
  '/editor/edit/layers/$layerId': typeof EditorLayoutEditLayersLayerIdRoute
  '/editor/edit/layers/add': typeof EditorLayoutEditLayersAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mapId': typeof MapIdLayoutViewIndexRoute
  '/editor': typeof EditorLayoutViewIndexRoute
  '/$mapId/basemap': typeof MapIdLayoutViewBasemapRoute
  '/$mapId/description': typeof MapIdLayoutViewDescriptionRoute
  '/$mapId/legend': typeof MapIdLayoutViewLegendRoute
  '/$mapId/manage': typeof MapIdLayoutViewManageRoute
  '/editor/basemap': typeof EditorLayoutViewBasemapRoute
  '/editor/description': typeof EditorLayoutViewDescriptionRoute
  '/editor/legend': typeof EditorLayoutViewLegendRoute
  '/editor/manage': typeof EditorLayoutViewManageRoute
  '/editor/edit/basemap': typeof EditorLayoutEditBasemapRoute
  '/editor/edit/description': typeof EditorLayoutEditDescriptionRoute
  '/editor/edit/manage': typeof EditorLayoutEditManageRoute
  '/editor/edit/settings': typeof EditorLayoutEditSettingsRoute
  '/editor/edit': typeof EditorLayoutEditIndexRoute
  '/$mapId/folders/$folderId': typeof MapIdLayoutViewFoldersFolderIdRoute
  '/$mapId/layers/$layerId': typeof MapIdLayoutViewLayersLayerIdRoute
  '/editor/folders/$folderId': typeof EditorLayoutViewFoldersFolderIdRoute
  '/editor/layers/$layerId': typeof EditorLayoutViewLayersLayerIdRoute
  '/editor/edit/folders/$folderId': typeof EditorLayoutEditFoldersFolderIdRoute
  '/editor/edit/folders/add': typeof EditorLayoutEditFoldersAddRoute
  '/editor/edit/layers/$layerId': typeof EditorLayoutEditLayersLayerIdRoute
  '/editor/edit/layers/add': typeof EditorLayoutEditLayersAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$mapId': typeof MapIdRouteWithChildren
  '/editor': typeof EditorRouteWithChildren
  '/$mapId/_layout': typeof MapIdLayoutRouteWithChildren
  '/editor/_layout': typeof EditorLayoutRouteWithChildren
  '/$mapId/_layout/_view': typeof MapIdLayoutViewRouteWithChildren
  '/editor/_layout/_view': typeof EditorLayoutViewRouteWithChildren
  '/editor/_layout/edit': typeof EditorLayoutEditRouteWithChildren
  '/$mapId/_layout/_view/basemap': typeof MapIdLayoutViewBasemapRoute
  '/$mapId/_layout/_view/description': typeof MapIdLayoutViewDescriptionRoute
  '/$mapId/_layout/_view/legend': typeof MapIdLayoutViewLegendRoute
  '/$mapId/_layout/_view/manage': typeof MapIdLayoutViewManageRoute
  '/editor/_layout/_view/basemap': typeof EditorLayoutViewBasemapRoute
  '/editor/_layout/_view/description': typeof EditorLayoutViewDescriptionRoute
  '/editor/_layout/_view/legend': typeof EditorLayoutViewLegendRoute
  '/editor/_layout/_view/manage': typeof EditorLayoutViewManageRoute
  '/editor/_layout/edit/basemap': typeof EditorLayoutEditBasemapRoute
  '/editor/_layout/edit/description': typeof EditorLayoutEditDescriptionRoute
  '/editor/_layout/edit/manage': typeof EditorLayoutEditManageRoute
  '/editor/_layout/edit/settings': typeof EditorLayoutEditSettingsRoute
  '/$mapId/_layout/_view/': typeof MapIdLayoutViewIndexRoute
  '/editor/_layout/_view/': typeof EditorLayoutViewIndexRoute
  '/editor/_layout/edit/': typeof EditorLayoutEditIndexRoute
  '/$mapId/_layout/_view/folders/$folderId': typeof MapIdLayoutViewFoldersFolderIdRoute
  '/$mapId/_layout/_view/layers/$layerId': typeof MapIdLayoutViewLayersLayerIdRoute
  '/editor/_layout/_view/folders/$folderId': typeof EditorLayoutViewFoldersFolderIdRoute
  '/editor/_layout/_view/layers/$layerId': typeof EditorLayoutViewLayersLayerIdRoute
  '/editor/_layout/edit/folders/$folderId': typeof EditorLayoutEditFoldersFolderIdRoute
  '/editor/_layout/edit/folders/add': typeof EditorLayoutEditFoldersAddRoute
  '/editor/_layout/edit/layers/$layerId': typeof EditorLayoutEditLayersLayerIdRoute
  '/editor/_layout/edit/layers/add': typeof EditorLayoutEditLayersAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$mapId'
    | '/editor'
    | '/editor/edit'
    | '/$mapId/basemap'
    | '/$mapId/description'
    | '/$mapId/legend'
    | '/$mapId/manage'
    | '/editor/basemap'
    | '/editor/description'
    | '/editor/legend'
    | '/editor/manage'
    | '/editor/edit/basemap'
    | '/editor/edit/description'
    | '/editor/edit/manage'
    | '/editor/edit/settings'
    | '/$mapId/'
    | '/editor/'
    | '/editor/edit/'
    | '/$mapId/folders/$folderId'
    | '/$mapId/layers/$layerId'
    | '/editor/folders/$folderId'
    | '/editor/layers/$layerId'
    | '/editor/edit/folders/$folderId'
    | '/editor/edit/folders/add'
    | '/editor/edit/layers/$layerId'
    | '/editor/edit/layers/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$mapId'
    | '/editor'
    | '/$mapId/basemap'
    | '/$mapId/description'
    | '/$mapId/legend'
    | '/$mapId/manage'
    | '/editor/basemap'
    | '/editor/description'
    | '/editor/legend'
    | '/editor/manage'
    | '/editor/edit/basemap'
    | '/editor/edit/description'
    | '/editor/edit/manage'
    | '/editor/edit/settings'
    | '/editor/edit'
    | '/$mapId/folders/$folderId'
    | '/$mapId/layers/$layerId'
    | '/editor/folders/$folderId'
    | '/editor/layers/$layerId'
    | '/editor/edit/folders/$folderId'
    | '/editor/edit/folders/add'
    | '/editor/edit/layers/$layerId'
    | '/editor/edit/layers/add'
  id:
    | '__root__'
    | '/'
    | '/$mapId'
    | '/editor'
    | '/$mapId/_layout'
    | '/editor/_layout'
    | '/$mapId/_layout/_view'
    | '/editor/_layout/_view'
    | '/editor/_layout/edit'
    | '/$mapId/_layout/_view/basemap'
    | '/$mapId/_layout/_view/description'
    | '/$mapId/_layout/_view/legend'
    | '/$mapId/_layout/_view/manage'
    | '/editor/_layout/_view/basemap'
    | '/editor/_layout/_view/description'
    | '/editor/_layout/_view/legend'
    | '/editor/_layout/_view/manage'
    | '/editor/_layout/edit/basemap'
    | '/editor/_layout/edit/description'
    | '/editor/_layout/edit/manage'
    | '/editor/_layout/edit/settings'
    | '/$mapId/_layout/_view/'
    | '/editor/_layout/_view/'
    | '/editor/_layout/edit/'
    | '/$mapId/_layout/_view/folders/$folderId'
    | '/$mapId/_layout/_view/layers/$layerId'
    | '/editor/_layout/_view/folders/$folderId'
    | '/editor/_layout/_view/layers/$layerId'
    | '/editor/_layout/edit/folders/$folderId'
    | '/editor/_layout/edit/folders/add'
    | '/editor/_layout/edit/layers/$layerId'
    | '/editor/_layout/edit/layers/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapIdRoute: typeof MapIdRouteWithChildren
  EditorRoute: typeof EditorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mapId': {
      id: '/$mapId'
      path: '/$mapId'
      fullPath: '/$mapId'
      preLoaderRoute: typeof MapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/_layout': {
      id: '/editor/_layout'
      path: ''
      fullPath: '/editor'
      preLoaderRoute: typeof EditorLayoutRouteImport
      parentRoute: typeof EditorRoute
    }
    '/$mapId/_layout': {
      id: '/$mapId/_layout'
      path: ''
      fullPath: '/$mapId'
      preLoaderRoute: typeof MapIdLayoutRouteImport
      parentRoute: typeof MapIdRoute
    }
    '/editor/_layout/edit': {
      id: '/editor/_layout/edit'
      path: '/edit'
      fullPath: '/editor/edit'
      preLoaderRoute: typeof EditorLayoutEditRouteImport
      parentRoute: typeof EditorLayoutRoute
    }
    '/editor/_layout/_view': {
      id: '/editor/_layout/_view'
      path: ''
      fullPath: '/editor'
      preLoaderRoute: typeof EditorLayoutViewRouteImport
      parentRoute: typeof EditorLayoutRoute
    }
    '/$mapId/_layout/_view': {
      id: '/$mapId/_layout/_view'
      path: ''
      fullPath: '/$mapId'
      preLoaderRoute: typeof MapIdLayoutViewRouteImport
      parentRoute: typeof MapIdLayoutRoute
    }
    '/editor/_layout/edit/': {
      id: '/editor/_layout/edit/'
      path: '/'
      fullPath: '/editor/edit/'
      preLoaderRoute: typeof EditorLayoutEditIndexRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/_view/': {
      id: '/editor/_layout/_view/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorLayoutViewIndexRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/$mapId/_layout/_view/': {
      id: '/$mapId/_layout/_view/'
      path: '/'
      fullPath: '/$mapId/'
      preLoaderRoute: typeof MapIdLayoutViewIndexRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/editor/_layout/edit/settings': {
      id: '/editor/_layout/edit/settings'
      path: '/settings'
      fullPath: '/editor/edit/settings'
      preLoaderRoute: typeof EditorLayoutEditSettingsRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/manage': {
      id: '/editor/_layout/edit/manage'
      path: '/manage'
      fullPath: '/editor/edit/manage'
      preLoaderRoute: typeof EditorLayoutEditManageRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/description': {
      id: '/editor/_layout/edit/description'
      path: '/description'
      fullPath: '/editor/edit/description'
      preLoaderRoute: typeof EditorLayoutEditDescriptionRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/basemap': {
      id: '/editor/_layout/edit/basemap'
      path: '/basemap'
      fullPath: '/editor/edit/basemap'
      preLoaderRoute: typeof EditorLayoutEditBasemapRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/_view/manage': {
      id: '/editor/_layout/_view/manage'
      path: '/manage'
      fullPath: '/editor/manage'
      preLoaderRoute: typeof EditorLayoutViewManageRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/editor/_layout/_view/legend': {
      id: '/editor/_layout/_view/legend'
      path: '/legend'
      fullPath: '/editor/legend'
      preLoaderRoute: typeof EditorLayoutViewLegendRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/editor/_layout/_view/description': {
      id: '/editor/_layout/_view/description'
      path: '/description'
      fullPath: '/editor/description'
      preLoaderRoute: typeof EditorLayoutViewDescriptionRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/editor/_layout/_view/basemap': {
      id: '/editor/_layout/_view/basemap'
      path: '/basemap'
      fullPath: '/editor/basemap'
      preLoaderRoute: typeof EditorLayoutViewBasemapRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/$mapId/_layout/_view/manage': {
      id: '/$mapId/_layout/_view/manage'
      path: '/manage'
      fullPath: '/$mapId/manage'
      preLoaderRoute: typeof MapIdLayoutViewManageRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/$mapId/_layout/_view/legend': {
      id: '/$mapId/_layout/_view/legend'
      path: '/legend'
      fullPath: '/$mapId/legend'
      preLoaderRoute: typeof MapIdLayoutViewLegendRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/$mapId/_layout/_view/description': {
      id: '/$mapId/_layout/_view/description'
      path: '/description'
      fullPath: '/$mapId/description'
      preLoaderRoute: typeof MapIdLayoutViewDescriptionRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/$mapId/_layout/_view/basemap': {
      id: '/$mapId/_layout/_view/basemap'
      path: '/basemap'
      fullPath: '/$mapId/basemap'
      preLoaderRoute: typeof MapIdLayoutViewBasemapRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/editor/_layout/edit/layers/add': {
      id: '/editor/_layout/edit/layers/add'
      path: '/layers/add'
      fullPath: '/editor/edit/layers/add'
      preLoaderRoute: typeof EditorLayoutEditLayersAddRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/layers/$layerId': {
      id: '/editor/_layout/edit/layers/$layerId'
      path: '/layers/$layerId'
      fullPath: '/editor/edit/layers/$layerId'
      preLoaderRoute: typeof EditorLayoutEditLayersLayerIdRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/folders/add': {
      id: '/editor/_layout/edit/folders/add'
      path: '/folders/add'
      fullPath: '/editor/edit/folders/add'
      preLoaderRoute: typeof EditorLayoutEditFoldersAddRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/edit/folders/$folderId': {
      id: '/editor/_layout/edit/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/editor/edit/folders/$folderId'
      preLoaderRoute: typeof EditorLayoutEditFoldersFolderIdRouteImport
      parentRoute: typeof EditorLayoutEditRoute
    }
    '/editor/_layout/_view/layers/$layerId': {
      id: '/editor/_layout/_view/layers/$layerId'
      path: '/layers/$layerId'
      fullPath: '/editor/layers/$layerId'
      preLoaderRoute: typeof EditorLayoutViewLayersLayerIdRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/editor/_layout/_view/folders/$folderId': {
      id: '/editor/_layout/_view/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/editor/folders/$folderId'
      preLoaderRoute: typeof EditorLayoutViewFoldersFolderIdRouteImport
      parentRoute: typeof EditorLayoutViewRoute
    }
    '/$mapId/_layout/_view/layers/$layerId': {
      id: '/$mapId/_layout/_view/layers/$layerId'
      path: '/layers/$layerId'
      fullPath: '/$mapId/layers/$layerId'
      preLoaderRoute: typeof MapIdLayoutViewLayersLayerIdRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
    '/$mapId/_layout/_view/folders/$folderId': {
      id: '/$mapId/_layout/_view/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/$mapId/folders/$folderId'
      preLoaderRoute: typeof MapIdLayoutViewFoldersFolderIdRouteImport
      parentRoute: typeof MapIdLayoutViewRoute
    }
  }
}

interface MapIdLayoutViewRouteChildren {
  MapIdLayoutViewBasemapRoute: typeof MapIdLayoutViewBasemapRoute
  MapIdLayoutViewDescriptionRoute: typeof MapIdLayoutViewDescriptionRoute
  MapIdLayoutViewLegendRoute: typeof MapIdLayoutViewLegendRoute
  MapIdLayoutViewManageRoute: typeof MapIdLayoutViewManageRoute
  MapIdLayoutViewIndexRoute: typeof MapIdLayoutViewIndexRoute
  MapIdLayoutViewFoldersFolderIdRoute: typeof MapIdLayoutViewFoldersFolderIdRoute
  MapIdLayoutViewLayersLayerIdRoute: typeof MapIdLayoutViewLayersLayerIdRoute
}

const MapIdLayoutViewRouteChildren: MapIdLayoutViewRouteChildren = {
  MapIdLayoutViewBasemapRoute: MapIdLayoutViewBasemapRoute,
  MapIdLayoutViewDescriptionRoute: MapIdLayoutViewDescriptionRoute,
  MapIdLayoutViewLegendRoute: MapIdLayoutViewLegendRoute,
  MapIdLayoutViewManageRoute: MapIdLayoutViewManageRoute,
  MapIdLayoutViewIndexRoute: MapIdLayoutViewIndexRoute,
  MapIdLayoutViewFoldersFolderIdRoute: MapIdLayoutViewFoldersFolderIdRoute,
  MapIdLayoutViewLayersLayerIdRoute: MapIdLayoutViewLayersLayerIdRoute,
}

const MapIdLayoutViewRouteWithChildren = MapIdLayoutViewRoute._addFileChildren(
  MapIdLayoutViewRouteChildren,
)

interface MapIdLayoutRouteChildren {
  MapIdLayoutViewRoute: typeof MapIdLayoutViewRouteWithChildren
}

const MapIdLayoutRouteChildren: MapIdLayoutRouteChildren = {
  MapIdLayoutViewRoute: MapIdLayoutViewRouteWithChildren,
}

const MapIdLayoutRouteWithChildren = MapIdLayoutRoute._addFileChildren(
  MapIdLayoutRouteChildren,
)

interface MapIdRouteChildren {
  MapIdLayoutRoute: typeof MapIdLayoutRouteWithChildren
}

const MapIdRouteChildren: MapIdRouteChildren = {
  MapIdLayoutRoute: MapIdLayoutRouteWithChildren,
}

const MapIdRouteWithChildren = MapIdRoute._addFileChildren(MapIdRouteChildren)

interface EditorLayoutViewRouteChildren {
  EditorLayoutViewBasemapRoute: typeof EditorLayoutViewBasemapRoute
  EditorLayoutViewDescriptionRoute: typeof EditorLayoutViewDescriptionRoute
  EditorLayoutViewLegendRoute: typeof EditorLayoutViewLegendRoute
  EditorLayoutViewManageRoute: typeof EditorLayoutViewManageRoute
  EditorLayoutViewIndexRoute: typeof EditorLayoutViewIndexRoute
  EditorLayoutViewFoldersFolderIdRoute: typeof EditorLayoutViewFoldersFolderIdRoute
  EditorLayoutViewLayersLayerIdRoute: typeof EditorLayoutViewLayersLayerIdRoute
}

const EditorLayoutViewRouteChildren: EditorLayoutViewRouteChildren = {
  EditorLayoutViewBasemapRoute: EditorLayoutViewBasemapRoute,
  EditorLayoutViewDescriptionRoute: EditorLayoutViewDescriptionRoute,
  EditorLayoutViewLegendRoute: EditorLayoutViewLegendRoute,
  EditorLayoutViewManageRoute: EditorLayoutViewManageRoute,
  EditorLayoutViewIndexRoute: EditorLayoutViewIndexRoute,
  EditorLayoutViewFoldersFolderIdRoute: EditorLayoutViewFoldersFolderIdRoute,
  EditorLayoutViewLayersLayerIdRoute: EditorLayoutViewLayersLayerIdRoute,
}

const EditorLayoutViewRouteWithChildren =
  EditorLayoutViewRoute._addFileChildren(EditorLayoutViewRouteChildren)

interface EditorLayoutEditRouteChildren {
  EditorLayoutEditBasemapRoute: typeof EditorLayoutEditBasemapRoute
  EditorLayoutEditDescriptionRoute: typeof EditorLayoutEditDescriptionRoute
  EditorLayoutEditManageRoute: typeof EditorLayoutEditManageRoute
  EditorLayoutEditSettingsRoute: typeof EditorLayoutEditSettingsRoute
  EditorLayoutEditIndexRoute: typeof EditorLayoutEditIndexRoute
  EditorLayoutEditFoldersFolderIdRoute: typeof EditorLayoutEditFoldersFolderIdRoute
  EditorLayoutEditFoldersAddRoute: typeof EditorLayoutEditFoldersAddRoute
  EditorLayoutEditLayersLayerIdRoute: typeof EditorLayoutEditLayersLayerIdRoute
  EditorLayoutEditLayersAddRoute: typeof EditorLayoutEditLayersAddRoute
}

const EditorLayoutEditRouteChildren: EditorLayoutEditRouteChildren = {
  EditorLayoutEditBasemapRoute: EditorLayoutEditBasemapRoute,
  EditorLayoutEditDescriptionRoute: EditorLayoutEditDescriptionRoute,
  EditorLayoutEditManageRoute: EditorLayoutEditManageRoute,
  EditorLayoutEditSettingsRoute: EditorLayoutEditSettingsRoute,
  EditorLayoutEditIndexRoute: EditorLayoutEditIndexRoute,
  EditorLayoutEditFoldersFolderIdRoute: EditorLayoutEditFoldersFolderIdRoute,
  EditorLayoutEditFoldersAddRoute: EditorLayoutEditFoldersAddRoute,
  EditorLayoutEditLayersLayerIdRoute: EditorLayoutEditLayersLayerIdRoute,
  EditorLayoutEditLayersAddRoute: EditorLayoutEditLayersAddRoute,
}

const EditorLayoutEditRouteWithChildren =
  EditorLayoutEditRoute._addFileChildren(EditorLayoutEditRouteChildren)

interface EditorLayoutRouteChildren {
  EditorLayoutViewRoute: typeof EditorLayoutViewRouteWithChildren
  EditorLayoutEditRoute: typeof EditorLayoutEditRouteWithChildren
}

const EditorLayoutRouteChildren: EditorLayoutRouteChildren = {
  EditorLayoutViewRoute: EditorLayoutViewRouteWithChildren,
  EditorLayoutEditRoute: EditorLayoutEditRouteWithChildren,
}

const EditorLayoutRouteWithChildren = EditorLayoutRoute._addFileChildren(
  EditorLayoutRouteChildren,
)

interface EditorRouteChildren {
  EditorLayoutRoute: typeof EditorLayoutRouteWithChildren
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorLayoutRoute: EditorLayoutRouteWithChildren,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapIdRoute: MapIdRouteWithChildren,
  EditorRoute: EditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
